// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Theoremone.SmartAc.Data;

#nullable disable

namespace Theoremone.SmartAc.Data.Migrations.Sqlite
{
    [DbContext(typeof(SmartAcContext))]
    [Migration("20230331010136_alert_date_time")]
    partial class alert_date_time
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.Device", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstRegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SerialNumber");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceAlert", b =>
                {
                    b.Property<int>("DeviceAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlertDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("AlertStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceReadingDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeviceReadingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeviceAlertId");

                    b.HasIndex("DeviceReadingId");

                    b.ToTable("DeviceAlerts");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceReading", b =>
                {
                    b.Property<int>("DeviceReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CarbonMonoxide")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Humidity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ReceivedDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperature")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("DeviceReadingId");

                    b.HasIndex("DeviceSerialNumber");

                    b.ToTable("DeviceReadings");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceRegistration", b =>
                {
                    b.Property<int>("DeviceRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceRegistrationId");

                    b.HasIndex("DeviceSerialNumber");

                    b.ToTable("DeviceRegistrations");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceAlert", b =>
                {
                    b.HasOne("Theoremone.SmartAc.Data.Models.DeviceReading", "DeviceReading")
                        .WithMany("DeviceAlerts")
                        .HasForeignKey("DeviceReadingId");

                    b.Navigation("DeviceReading");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceReading", b =>
                {
                    b.HasOne("Theoremone.SmartAc.Data.Models.Device", "Device")
                        .WithMany("DeviceReadings")
                        .HasForeignKey("DeviceSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceRegistration", b =>
                {
                    b.HasOne("Theoremone.SmartAc.Data.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.Device", b =>
                {
                    b.Navigation("DeviceReadings");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceReading", b =>
                {
                    b.Navigation("DeviceAlerts");
                });
#pragma warning restore 612, 618
        }
    }
}
